### ISSUE TITLE
Это должно быть в константах, а не строками

### ISSUE THREAD

**Issue by coursar** [abdurashidovtaha/cashback-2#2]
https://github.com/abdurashidovtaha/cashback-2/blob/26b02f5c01598c0c5de019a9c726d4d9a11a6c92/src/js/app.js#L3

**Comment by abdurashidovtaha** [comment]
Я сначала исправил ошибку, затем закомитил неправильно(не добавил ID)-пришлось поменять одну сумму, чтобы заново закомитить, но с ID.

**Comment by coursar** [comment]
Закрывайте, если сделали
